#8004表示注册到zookeeper服务器的服务提供者端口号
server:
  port: 8081
 
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: zk-test1
  cloud:
    zookeeper:
      connect-string: 111.229.97.109:7320,118.89.115.139:7320,106.54.229.34:7320
      discovery:
        enabled: true
        # 服务实例注册进zookeeper的host
        instance-host: 127.0.0.1
